### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Max-ctr** [leedave/flipper-zero-cross-remote#13]
Flipper zero 0.98.2[01-02-24]
When run saved command chain app is crash.
Flipper crashed and was rebooted usage fault.

**Comment by Max-ctr** [comment]
![IMG_3546](https://github.com/leedave/flipper-zero-cross-remote/assets/70106324/3b062c95-2255-44ab-b87a-b48e54c2c490)

**Comment by leedave** [comment]
I'm unaware of that fault. But the problem is, it can also be connected to whatever was run before on Flipper. Maybe the IR or SubGhz hardware was blocked, that would be a typical reason for that kind of message. 

- Can you add steps to reproduce it? Does it happen every time you run the chain or only once? 
- What kind of command chain are you running? Type of commands, how many commands, example file?
- Are you using the latest version of Cross Remote (2.3)

If I can reproduce the issue, I'll search for a fix.

**Comment by Max-ctr** [comment]
- this happens every time when I try to start a command chain consisting of 3 SubGhz signals.
-application version 2.3
- modules are not blocked, as I can use them
[xremote.conf.txt](https://github.com/leedave/flipper-zero-cross-remote/files/14152258/xremote.conf.txt)
[Test2.xr.txt](https://github.com/leedave/flipper-zero-cross-remote/files/14152260/Test2.xr.txt)

**Comment by leedave** [comment]
Can you send me lamp_1 2 and 3?

**Comment by Max-ctr** [comment]
[Lamp_1.sub.txt](https://github.com/leedave/flipper-zero-cross-remote/files/14152399/Lamp_1.sub.txt)
[Lamp_2.sub.txt](https://github.com/leedave/flipper-zero-cross-remote/files/14152400/Lamp_2.sub.txt)
[Lamp_3.sub.txt](https://github.com/leedave/flipper-zero-cross-remote/files/14152401/Lamp_3.sub.txt)

**Comment by leedave** [comment]
Interesting, I didn't have a file to test subghz implementations built like that yet. In place of a predefined signal to be played, it actually works more like IR where the signal repeats as long as you press the button. 

I think it may be worth implementing support for that, but it's nothing I can do fast. 

As a workaround for now, I made you a raw file combining short burst of Lamp1, Lamp2 and Lamp3. Just put it into a cross remote command chain (remove the .txt ending first) and see if all 3 lamps turn on. 


[Lamps_raw.sub.txt](https://github.com/leedave/flipper-zero-cross-remote/files/14156187/Lamps_raw.sub.txt)

**Comment by Max-ctr** [comment]
Interestingly, the raw signals recorded by the flipper can easily be placed in a chain and everything will work. but I would like to see such functionality so that it would be possible to create chains of all types of signals. it would be cool! Thanks for the raw file

**Comment by mtmerk14** [comment]
Been getting this issue as well thought I could provide a little information that might help.
When mine crashes doing the same process sometimes it gives the the same "UsageFault" and other times it gives a "NULL pointer dereference" fault
(edit: recording a raw file, and using that does work in the in the chain)
![flpr-2024-02-04-051536](https://github.com/leedave/flipper-zero-cross-remote/assets/9925217/489b7487-56d0-46d0-8521-c8825162a773)

**Comment by leedave** [comment]
Could be related to the fact that subghz runs async. So whatever issue reads first determines the error. 
But yes, I‘ll add support for encoded subghz to my future development. For now just use RAW.

**Comment by leedave** [comment]
Thank you for the great inputs. I've updated the app to now handle encoded SubGhz files. 
You can set a timer for signal length in the settings, I put in a default of 500ms in as I think that should be enough for SubGhz. But please test it out and give feedback. 

Note, it is possible that on first enter/exit the app crashes, the app crashes. That is because of the new options in settings. It will only happen once.

**Comment by Max-ctr** [comment]
Thanks for the quick response and quick action.
When the application is updated in flippernet and mobile app?

**Comment by leedave** [comment]
It's already submitted. Just a question of when flipper devs have a spare minute to accept it. 

It's usually done pretty fast. They do a great job.

**Comment by Max-ctr** [comment]
Thank you, you are doing a great job too.

**Comment by leedave** [comment]
It's available now

**Comment by Max-ctr** [comment]
woah!!! its working!!!! cool!

**Comment by mtmerk14** [comment]
You are awesome! Thank you!
